language: java
jdk: openjdk11
os: linux
dist: bionic

services:
  - postgresql

addons:
  postgresql: "10"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $TRAVIS_BUILD_DIR/nimrod/build/agents/

before_script:
  - psql -c "CREATE ROLE nimrod LOGIN PASSWORD 'nimrod';" -U postgres
  - psql -c "CREATE DATABASE nimrod OWNER nimrod;" -U postgres

env:
  - >
    NIMRODG_TEST_PGUSER=nimrod
    NIMRODG_TEST_PGPASSWORD=nimrod
    NIMRODG_TEST_PGHOST=127.0.0.1
    NIMRODG_TEST_PGDATABASE=nimrod

script:
  - ./gradlew --no-daemon --info check generateArtifacts

# See https://github.com/travis-ci/travis-ci/issues/8667
install: true

deploy:
  provider: releases
  token:
    secure: EZIKib7ApY8+o5IgfplecwA3ioCi8Vza/Y3Ly85jf1F6lw3o6yaEaCw5J8cYp9JbhjYHVMA/eVrqbi77ReGL9W/gNuzvvU0Ca7RVeZ2F0iF/oqXOsD0OpTq+M0U70fyGYgB24oPYih1+4NyZusCWIWn7e3o7DYBc6L3plCR/sF0Q7IF7tIGJ2H3HCU26feSIddVRFCbii6428I4z5nyFcEC2FJAZfT5HOzlhJAmC6oxo8z+Tr3r/UKcZCNx6sSyogrQO32RoFr7Ym1HLJrimoLPutwnjbJYx1FsemtOu7UlV+xdvgwFKfPTSivvFrlr019Eh0DDqSc26GubiONkNwYk93yKC8ZCOUj2BtVvbxFuzG3IwWwf9Apsht5DValy2Htu8CfLaeC28qQJaesOU0ooPAXqyglTh5cAcMcVjB61rvqOj6ssGmCYVY9L807rd2AZrB2SjLZeUwv05QeN9396PW81sR+5ioeDrKJMbean4+nFkOOR71Jccs0IqGNu+oH0KkE18Y+Ajcacc990YCXpNwc4dYkZhMEJxNlA9AhFkWPYyae+P21rjs3QizSN2sYImVJrg9YszbIvb+s1fQ+IG/EoOyJqo6klnJqSI3Tza/iXP38FeXhvBEVvzTtqgsH+SSYWDADVTYER/MSk/fofykvDtMbr6FvLMyV4zwvQ=
  file_glob: true
  file:
    - nimrod/build/distributions/nimrod-*.tar.*
    - nimrod/build/distributions/nimrod_*-0ubuntu1_all.deb
    - nimrod/build/distributions/nimrod-*.rpm
  on:
    tags: true
  cleanup: false
  # Until dplv2
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: LiBFvjUjdtKqfhxJVC6ULIcS8q/s3FLyjVhlJuhvFmruApInq7GLU9bgetfHn6Hv62N6NROWSHqfMK8U5K7RWkEA3w0r1uD0xK6kkv2N2Wa2m8z8aS5RYLlHJKFSBdO4j0wb57b8FQZ3qfFi5ETzLzdaEqrEScf0MDylu3y1rbAtuQxI47geUEMKPPs0+REHGRF/TPWZhbm79Sr59LogHB6fy3trYDVTyVj8FaZdV67m481PMhVI75RinpAcEhPnZUNu0iBRVSVJ3PxxKXxgd2GX61BWLwg4fCVcKwbdSLglkh6ZqilJ6YrTPf7ko1zumdUq0sd8aM7IkQpoFi+yf6apMN+k8brHtg3Yrq1pa4h2ERKws6kCccOxZupJE/Mqz4thR6JREuq+NZ1zK68MyvItb8cz3B/EYEJCixtFyGTUcGQhqcNx00+g2H2rDtSNYItHqPDhi8itnWJjIWeDblFIlyOfj6hHuD44lekDM+bs38mHgl45MHkkLgEP1VzWRsAMSDebXd6/weimB9JOhv36pAw1WZ2sRxIsu4OqLCdkaFZTSq9rql5rjc4lKMMJZAl9DrAVv0kE0CPuedVktELb9GmgNf8KmgBRH8aYNzM85mX3ov28+tiVh1g6wnSEsgNi04djuHhnrcEkaeNj/RG0wF9X7HSQuHbEUzwDj/g=
    on_success: always
    on_failure: always
