#!/bin/sh

set -e

if [ "${1}" = "purge" ] ; then
	if [ -d /var/lib/nimrod-portal-backend ]; then
		rm -rf /var/lib/nimrod-portal-backend
	fi
	if [ -d /var/log/nimrod-portal-backend ]; then
		rm -rf /var/log/nimrod-portal-backend
	fi
	if [ -d /etc/nimrod-portal-backend ]; then
		rm -rf /etc/nimrod-portal-backend
	fi
fi

# Automatically added by dh_installsystemd/11.1.6ubuntu2
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/11.1.6ubuntu2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'nimrod-portal-backend.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'nimrod-portal-backend.service' >/dev/null || true
		deb-systemd-helper unmask 'nimrod-portal-backend.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
