name: Build & Test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10-alpine
        env:
          POSTGRES_DB: nimrod
          POSTGRES_PASSWORD: nimrod
          POSTGRES_USER: nimrod
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Work around https://github.com/actions/checkout/issues/290
      - run: git fetch --force --tags

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            nimrod/build/agents
          key: gradle-cache
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: chmod +x gradlew
      - run: ./gradlew --no-daemon --info assemble
      - run: ./gradlew --no-daemon --info test
        env:
          NIMRODG_TEST_PGUSER: nimrod
          NIMRODG_TEST_PGPASSWORD: nimrod
          NIMRODG_TEST_PGHOST: 127.0.0.1
          NIMRODG_TEST_PGDATABASE: nimrod
      - run: ./gradlew --no-daemon --info generateArtifacts
      - uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: nimrod/build/distributions/*

  deploy:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-artifacts
          path: dist
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
